<?php
	$class = $this->getClass();
?>
<table border=0 cellpadding=4 cellspacing=4>
	<tr>
		<th style="font-size: 1.6em;">
			Class
		</th>
	</tr>
	<tr>
		<td style="font-weight: bold;">
			Class Name:
		</td>
		<td>
			<?php echo $class['fileParts']['className']; ?>
		</td>
	</tr>
	<tr>
		<td style="font-weight: bold;">
			Parent(s):
		</td>
		<td>
			<?php
				if($class['parents']) {
					echo implode(', ', $class['parents']);
				}
			?>
		</td>
	</tr>
	<tr>
		<td style="font-weight: bold;">
			Implemented In:
		</td>
		<td>
			<?php echo $class['filePath']; ?>
		</td>
	</tr>
	<tr>
		<td style="font-weight: bold;">
			Factory Method:
		</td>
		<td>
			<?php
				$method = "Mage::helper('" . $class['groupName'];
				if($class['alias'] != 'data') {
					$method .= '/' . $class['alias'];
				}
				echo $method . "')";
			?>
		</td>
	</tr>
	<?php if(is_array($class['rewrite']) && sizeof($class['rewrite']) > 0) : ?>
	<tr>
		<?php if(array_key_exists('by', $class['rewrite'])) : ?>
		<td style="font-weight: bold;">
			Rewrite By:
		</td>
		<td>
			<?php echo $class['rewrite']['by']; ?>
		</td>
		<?php elseif(array_key_exists('for', $class['rewrite'])) : ?>
		<td style="font-weight: bold;">
			Rewrite For:
		</td>
		<td>
			<?php echo $class['rewrite']['for']; ?>
		</td>
		<?php endif; ?>
	</tr>
	<?php endif; ?>
</table>

<hr style="margin-top: 12px; margin-bottom: 6px;"/>

<table border=0 cellpadding=4 cellspacing=4>
	<tr>
		<th style="font-size: 1.6em;">
			Methods
		</th>
	</tr>
</table>