<?php
	$class = $this->getClass();
?>
<table border=0 cellpadding=4 cellspacing=4>
	<tr>
		<th colspan=2 style="font-size: 1.6em;">
			Class
		</th>
	</tr>
	<tr>
		<td style="font-weight: bold;">
			Class Name:
		</td>
		<td>
			<?php echo $class['fileParts']['className']; ?>
		</td>
	</tr>
	<tr>
		<td style="font-weight: bold;">
			Parent(s):
		</td>
		<td>
			<?php
				if($class['parents']) {
					echo implode(', ', $class['parents']);
				}
			?>
		</td>
	</tr>
	<tr>
		<td style="font-weight: bold;">
			Implemented In:
		</td>
		<td>
			<?php echo $class['filePath']; ?>
		</td>
	</tr>
	<tr>
		<td style="font-weight: bold;">
			Factory Method:
		</td>
		<td>
			<?php
				$method = "Mage::helper('" . $class['groupName'];
				if($class['alias'] != 'data') {
					$method .= '/' . $class['alias'];
				}
				echo $method . "')";
			?>
		</td>
	</tr>
	<?php if(is_array($class['rewrite']) && sizeof($class['rewrite']) > 0) : ?>
	<tr>
		<?php if(array_key_exists('by', $class['rewrite'])) : ?>
		<td style="font-weight: bold;">
			Rewrite By:
		</td>
		<td>
			<?php echo $class['rewrite']['by']; ?>
		</td>
		<?php elseif(array_key_exists('for', $class['rewrite'])) : ?>
		<td style="font-weight: bold;">
			Rewrite For:
		</td>
		<td>
			<?php echo $class['rewrite']['for']; ?>
		</td>
		<?php endif; ?>
	</tr>
	<?php endif; ?>
	<tr>
		<td style="font-weight: bold;">
			<a href="" onclick="$('class_doc_comment').toggle();return false;">Doc Comment:</a>
		</td>
		<td>
			<span id="class_doc_comment" style="display: none;"><pre><?php echo $class['docComment']; ?></pre></span>
		</td>
	</tr>
</table>

<hr style="margin-top: 12px; margin-bottom: 6px;"/>

<!--
$line['name']
$line['modifiers']
$line['parameters']
$line['docComment']
-->

<table border=0 cellpadding=4 cellspacing=4>
	<tr>
		<th style="font-size: 1.6em;" colspan="2">
			<a href="" onclick="$('methods_body').toggle();return false;">Methods</a>
		</th>
	</tr>
	<tbody id="methods_body" style="display: '';">
		<tr>
			<td colspan="2">
				<table border=0 cellpadding=4 cellspacing=4>
					<?php foreach($class['methods']['own_methods'] as $classMethod) : ?>
						<tr>
							<td style="width: 4px;">
								&nbsp;
							</td>
							<td colspan="2">
								<a href="" onclick="return moreIsLess('more_own_<?php echo $classMethod['name']; ?>', this)">more...</a>
							</td>
							<td>
								<?php echo implode(' ', $classMethod['modifiers']); ?>
								<?php echo $classMethod['name'] . $this->parseParameters($classMethod['parameters']); ?>
							</td>
						</tr>
						<tbody id="more_own_<?php echo $classMethod['name']; ?>" style="display: none;">
							<tr>
								<td style="width: 4px;">
								</td>
								<td>
								</td>
								<td style="width: 4px;">
								</td>
								<td>
									Implemented in: <?php echo $classMethod['fileName'] . ' on lines: ' .  $classMethod['lineStart'] .
														' - ' . $classMethod['lineEnd']; ?>
								</td>
							</tr>
							<tr>
								<td style="width: 4px;">
								</td>
								<td>
								</td>
								<td style="width: 4px;">
								</td>
								<td>
									<pre><?php echo $classMethod['docComment']; ?></pre>
								</td>
							</tr>
						</tbody>
					<?php endforeach; ?>
				</table>
			</td>
		</tr>
		<?php foreach($class['methods']['inherited'] as $name => $parentClass) : ?>
			<tr>
				<td style="width: 4px;">
					&nbsp;
				</td>
				<td>
					<table border=0 cellpadding=4 cellspacing=4>
						<tr>
							<th colspan="3" style="font-size: 1.2em;">
								Inherited from: <a href="" onclick="$('inherited_<?php echo $name; ?>').toggle();return false;">
									<?php echo $name; ?>
								</a>
							</th>
						</tr>
						<tbody id="inherited_<?php echo $name; ?>" style="display: none;">
							<tr>
								<td style="width: 4px;">
									&nbsp;
								</td>
								<td>
									<table border=0 cellpadding=4 cellspacing=4>
										<?php foreach($parentClass as $method) : ?>
											<tr>
												<td>
													<a href="" onclick="return moreIsLess('more_inherited_<?php echo $method['name']; ?>', this)">more...</a>
												</td>
												<td>
													<?php echo implode(' ', $method['modifiers']); ?>
													<?php echo $method['name'] . $this->parseParameters($method['parameters']); ?>
												</td>
											</tr>
											<tbody id ="more_inherited_<?php echo $method['name']; ?>" style="display: none;">
												<tr>
													<td>
													</td>
													<td>
														Implemented in: <?php echo $method['fileName'] . ' on lines: ' .  $method['lineStart'] .
														' - ' . $method['lineEnd']; ?>
													</td>
												</tr>
												<tr>
													<td>
													</td>
													<td>
														<pre><?php echo $method['docComment']; ?></pre>
													</td>
												</tr>
											</tbody>
										<?php endforeach; ?>
									</table>
								</td>
							</tr>
						</tbody>
					</table>
				</td>
			</tr>
		<?php endforeach; ?>
	</tbody>
</table>

<table border=0 cellpadding=4 cellspacing=4>
	<tr>
		<th style="font-size: 1.6em;" colspan="2">
			<a href="" onclick="$('constants_body').toggle();return false;">Constants</a>
		</th>
	</tr>
	<tbody id="constants_body" style="display: '';">
		<?php foreach($class['constants'] as $constant => $value) : ?>
		<tr>
			<td style="width: 4px;">
				&nbsp;
			</td>
			<td>
				<?php echo $constant . ' = ' . $value; ?>
			</td>
		</tr>
		<?php endforeach; ?>
	</tbody>
</table>

<table border=0 cellpadding=4 cellspacing=4>
	<tr>
		<th style="font-size: 1.6em;" colspan="2">
			<a href="" onclick="$('props_body').toggle();return false;">Properties</a>
		</th>
	</tr>
	<tbody id="props_body" style="display: '';">
		<tr>
			<td colspan="2">
				<table border=0 cellpadding=4 cellspacing=4>
					<?php foreach($class['properties']['own_props'] as $classProp) : ?>
						<tr>
							<td style="width: 4px;">
								&nbsp;
							</td>
							<td colspan="2">
								<a href="" onclick="return moreIsLess('more_own_prop<?php echo $classProp['name']; ?>', this)">more...</a>
							</td>
							<td>
								<?php echo implode(' ', $classProp['modifiers']); ?>
								<?php echo $classProp['name']; ?>
								<?php if($classProp['default']) echo ' = ' . $classProp['default']; ?>
							</td>
						</tr>
						<tbody id="more_own_prop<?php echo $classProp['name']; ?>" style="display: none;">
							<tr>
								<td style="width: 4px;">
								</td>
								<td>
								</td>
								<td style="width: 4px;">
								</td>
								<td>
									Implemented in: <?php echo $classProp['fileName']; ?>
								</td>
							</tr>
							<tr>
								<td style="width: 4px;">
								</td>
								<td>
								</td>
								<td style="width: 4px;">
								</td>
								<td>
									<pre><?php echo $classProp['docComment']; ?></pre>
								</td>
							</tr>
						</tbody>
					<?php endforeach; ?>
				</table>
			</td>
		</tr>
		<?php foreach($class['properties']['inherited'] as $name => $parentClass) : ?>
			<tr>
				<td style="width: 4px;">
					&nbsp;
				</td>
				<td>
					<table border=0 cellpadding=4 cellspacing=4>
						<tr>
							<th colspan="3" style="font-size: 1.2em;">
								Inherited from: <a href="" onclick="$('inherited_prop<?php echo $name; ?>').toggle();return false;">
									<?php echo $name; ?>
								</a>
							</th>
						</tr>
						<tbody id="inherited_prop<?php echo $name; ?>" style="display: none;">
							<tr>
								<td style="width: 4px;">
									&nbsp;
								</td>
								<td>
									<table border=0 cellpadding=4 cellspacing=4>
										<?php foreach($parentClass as $prop) : ?>
											<tr>
												<td>
													<a href="" onclick="return moreIsLess('more_inherited_props<?php echo $prop['name']; ?>', this)">more...</a>
												</td>
												<td>
													<?php echo implode(' ', $prop['modifiers']); ?>
													<?php echo $prop['name']; ?>
												</td>
											</tr>
											<tbody id ="more_inherited_props<?php echo $prop['name']; ?>" style="display: none;">
												<tr>
													<td>
													</td>
													<td>
														Implemented in: <?php echo $prop['fileName']; ?>
													</td>
												</tr>
												<tr>
													<td>
													</td>
													<td>
														<pre><?php echo $prop['docComment']; ?></pre>
													</td>
												</tr>
											</tbody>
										<?php endforeach; ?>
									</table>
								</td>
							</tr>
						</tbody>
					</table>
				</td>
			</tr>
		<?php endforeach; ?>
	</tbody>
</table>

<hr style="margin-top: 12px; margin-bottom: 6px;"/>