<h1>About Developer Manual</h1>
<script type="text/javascript">
	document.write('<scr' + 'ipt type="text/javascript" src="http://alanstorm.com/2011/promos/developer_menu/about.js"></scr' + 'ipt>');
</script>
<noscript>
	The about page is loaded from an external URL to allow
real-time reporting of project updates. You may also view 
<a href="http://alanstorm.com/2011/promos/developer_menu/about-source.html">the
page</a> directly.
</noscript>