<?php
$model = Mage::getModel('alanstormdotcom_developermanual/source_helper');
$codePoolOptions = $model->getCodePools();
?>
<h1>Helper Methods Reference</h1>
<div id="selects">
	<span style="float: left; margin-right: 8px;">
		<div style="font-weight: bold;">CodePool</div>
		<div>
			<select id="codepool_select">
				<?php echo $codePoolOptions; ?>
			</select>
		</div>
	</span>
	<span id="namespace_span" style="display: none; float: left; margin-right: 8px;">
		<div style="font-weight: bold;">NameSpace</div>
		<div>
			<select id="namespace_select">
				
			</select>
		</div>
	</span>
	<span id="module_span" style="display: none; float: left; margin-right: 8px;">
		<div style="font-weight: bold;">Module</div>
		<div>
			<select id="module_select"></select>
		</div>
	</span>
	<span id="helper_span" style="display: none; float: left; margin-right: 8px;">
		<div style="font-weight: bold;">Helper</div>
		<div>
			<select id="helper_select"></select>
		</div>
	</span>
</div>
<div style="clear: both;"></div>
<hr style="margin-top: 12px; margin-bottom: 6px;"/>
<div id="result">
	
</div>


