<style type="text/css">
hr {
    margin-bottom: 6px;
    margin-top: 12px;
}

table {
    border: 0;
    border-collapse: collapse;
    margin-top: 8px;
}

td {
    margin: 4px;
    padding: 4px;
}

td.tab {
    width: 4px;
}

a.more {
    color: #666666;
}

th.label {
    font-size: 1.6em;
}

th.label-small {
    font-size: 1.2em;
}

td.label {
    font-weight: bold;
}

span.select {
    float: left;
    margin-right: 8px;
}

div.label {
    font-weight: bold;
}

.clear {
    clear: both;
}
</style>